# 패키지 임포트

In [1]:
from C010_01_review_python_functions import *

import multiprocessing
import os
import pandas
import sqlite3

# 주석 처리

In [2]:
# 한 줄 주석
'''
여러 줄 주석은 이렇게 쓰거나
또는....
'''
"""
이렇게 작성합니다.
예시로 작성했습니다.
"""

'\n이렇게 작성합니다.\n예시로 작성했습니다.\n'

# 데이터 유형

In [3]:
# =====================================================================================================================================
# 예제로 사용할 값입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
value1 = 1.1
value2 = '1.2'
value3 = 1.3
value4 = 1
value5 = 0
# =====================================================================================================================================

# =====================================================================================================================================
# 정수/실수/참거짓/문자열 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('정수 유형')
print('실제 값', value1, '(', type(value1), ')을 정수로 표현하면', int(value1), '입니다.')
print('----------------------------------------------------------------------------------------------------')
print('실수 유형')
print('실제 값', value2, '(', type(value2), ')을 실수로 표현하면', float(value2), '입니다.')
print('----------------------------------------------------------------------------------------------------')
print('참/거짓 유형')
print('실제 값', value4, '(', type(value4), ')을 참/거짓으로 표현하면', bool(value4), '입니다.')
print('실제 값', value5, '(', type(value5), ')을 참/거짓으로 표현하면', bool(value5), '입니다.')
print('----------------------------------------------------------------------------------------------------')
print('문자 유형')
print('실제 값', value3, '(', type(value3), ')을 문자열로 표현하면', str(value3), '입니다.')
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# set 유형 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
set_sample = set()
set_sample.add(1)
set_sample.add(2)
set_sample.add(3)
set_sample.add(4)
set_sample.add(5)
set_sample.add(1)
print('----------------------------------------------------------------------------------------------------')
print('set 유형 (값이 중복되지 않습니다.)')
print(set_sample)
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# list 유형 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
list_sample = list()
list_sample.append(1)
list_sample.append(2)
list_sample.append(3)
list_sample.append(4)
list_sample.append(5)
list_sample.append(1)
print('----------------------------------------------------------------------------------------------------')
print('list 유형 (중복을 허용합니다.)')
print(list_sample)
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# dict 유형 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
dict_sample = dict()
dict_sample['key:1'] = 1
dict_sample['key:2'] = 2
dict_sample['key:3'] = 3
dict_sample['key:4'] = 4
dict_sample['key:5'] = 5
dict_sample['key:1'] = 6
print('----------------------------------------------------------------------------------------------------')
print('dict 유형 (key 에서는 중복을 허용하지 않고, value에서는 중복을 허용합니다.)')
print(dict_sample)
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# DataFrame 유형 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
df_sample = pandas.DataFrame([
    {'C1':1, 'C2':2},
    {'C1':3, 'C2':4},
    {'C1':5, 'C2':6},
    {'C1':7, 'C2':8},
])
print('----------------------------------------------------------------------------------------------------')
print('DataFrame 유형 (jupyter에서는 display를 사용하면 조금 더 확인이 쉽습니다.')
display(df_sample)
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# Series 유형 예시입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('Series 유형 (DataFrame의 부분 집합입니다.)')
print(type(df_sample['C1']), df_sample['C1'])
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

----------------------------------------------------------------------------------------------------
정수 유형
실제 값 1.1 ( <class 'float'> )을 정수로 표현하면 1 입니다.
----------------------------------------------------------------------------------------------------
실수 유형
실제 값 1.2 ( <class 'str'> )을 실수로 표현하면 1.2 입니다.
----------------------------------------------------------------------------------------------------
참/거짓 유형
실제 값 1 ( <class 'int'> )을 참/거짓으로 표현하면 True 입니다.
실제 값 0 ( <class 'int'> )을 참/거짓으로 표현하면 False 입니다.
----------------------------------------------------------------------------------------------------
문자 유형
실제 값 1.3 ( <class 'float'> )을 문자열로 표현하면 1.3 입니다.
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
set 유형 (값이 중복되지 않습니다.)
{1, 2, 3, 4, 5}
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
list 유형 (중복을 허용합니다.)
[1, 2, 3, 4, 5, 1]
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
dict 유형 (key 에서는 중복을 허용하지 않고, value에서는 중복을 허용합니다.)
{'key:1': 6, 'key:2': 2, 'key:3': 3, 'key:4': 4, 'key:5': 5}
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
DataFrame 유형 (jupyter에서는 display를 사용하면 조금 더 확인이 쉽습니다.

   C1  C2
0   1   2
1   3   4
2   5   6
3   7   8

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Series 유형 (DataFrame의 부분 집합입니다.)
<class 'pandas.core.series.Series'> 0    1
1    3
2    5
3    7
Name: C1, dtype: int64
----------------------------------------------------------------------------------------------------

# 조건문

In [4]:
value1 = 1
value2 = 3.2
value3 = True
value4 = 'XX'

# =====================================================================================================================================
# 정수 값을 비교합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
condition_value = 2
if value1 > condition_value:
    print('value1 은 ', condition_value, '보다 작습니다.')
elif value1 == condition_value:
    print('value1 은 ', condition_value, '과 같습니다.')
else:
    print('value1 은 ', condition_value, '보다 큽니다.')
# =====================================================================================================================================

# =====================================================================================================================================
# 실수 값을 비교합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
condition_value = 3
if value2 > condition_value:
    print('value2 은 ', condition_value, '보다 작습니다.')
elif value2 == condition_value:
    print('value2 은 ', condition_value, '과 같습니다.')
else:
    print('value2 은 ', condition_value, '보다 큽니다.')
# =====================================================================================================================================

# =====================================================================================================================================
# 참거짓 값을 비교합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
if value3:
    print('value3 은 ', value3, '참입니다.')
else:
    print('value3 은 ', value3, '거짓입니다.')
# =====================================================================================================================================

# =====================================================================================================================================
# 문자열 값을 비교합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
condition_value = 'YY'
if value4 > condition_value:
    print('value4 은 ', condition_value, '보다 작습니다.')
elif value4 == condition_value:
    print('value4 은 ', condition_value, '과 같습니다.')
else:
    print('value4 은 ', condition_value, '보다 큽니다.')
# =====================================================================================================================================

value1 은  2 보다 큽니다.
value2 은  3 보다 작습니다.
value3 은  True 참입니다.
value4 은  YY 보다 큽니다.

# 반복문

In [5]:
# =====================================================================================================================================
# For 구문입니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
list_to_log = list()
for index in range(10):
    list_to_log.append(index)
print(list_to_log)
# =====================================================================================================================================

# =====================================================================================================================================
# While 구문 입니다. (무한 반복을 주의합니다.)
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
list_to_log = list()
MAX_LOOP_COUNT = 10
flag_loop = True
loop_count = 0
while flag_loop:
    list_to_log.append(loop_count)
    loop_count += 1
    if loop_count > MAX_LOOP_COUNT:
        flag_loop = False
print(list_to_log)
# =====================================================================================================================================

# =====================================================================================================================================
# Do-While 구문 입니다. (파이썬에는 없습니다.)
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
list_to_log = list()
MAX_LOOP_COUNT = 10
flag_loop = True
loop_count = 0
list_to_log.append(loop_count)
loop_count += 1
while flag_loop:
    list_to_log.append(loop_count)
    loop_count += 1
    if loop_count > MAX_LOOP_COUNT:
        flag_loop = False
print(list_to_log)
# =====================================================================================================================================
print('----------------------------------------------------------------------------------------------------')

----------------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
----------------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
----------------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
----------------------------------------------------------------------------------------------------

# 예외 처리

In [6]:
value1 = '1.2'
try:
    print('문자열( 값:', value1, ')을 정수 유형으로 변경합니다.')
    print('값을 출력합니다. [', int(value1), ']')
    print('첫 시도에서 데이터 유형 변경에 성공하였습니다.')
except:
    print('데이터 유형 변환에 실패하여, 실수형으로 먼저 변경한 후 정수형으로 변경합니다.')
    print('값을 출력합니다. [', int(float(value1)), ']')
    print('예외 처리로 데이터 유형 변경에 성공하였습니다.')

문자열( 값: 1.2 )을 정수 유형으로 변경합니다.
데이터 유형 변환에 실패하여, 실수형으로 먼저 변경한 후 정수형으로 변경합니다.
값을 출력합니다. [ 1 ]
예외 처리로 데이터 유형 변경에 성공하였습니다.

# 함수

In [7]:
def function_sample(p_args):
    print(type(p_args), p_args)

value1 = 1
value2 = 1.2
value3 = '2.3'
value4 = {'key': 'value'}
value5 = ['element']

function_sample(value1)
function_sample(value2)
function_sample(value3)
function_sample(value4)
function_sample(value5)

<class 'int'> 1
<class 'float'> 1.2
<class 'str'> 2.3
<class 'dict'> {'key': 'value'}
<class 'list'> ['element']

# 클래스

In [8]:
class class_sample():
    def method_sample(self, p_args):
        print(type(p_args), p_args)

value1 = 1
value2 = 1.2
value3 = '2.3'
value4 = {'key': 'value'}
value5 = ['element']

sample = class_sample()
sample.method_sample(value1)
sample.method_sample(value2)
sample.method_sample(value3)
sample.method_sample(value4)
sample.method_sample(value5)

<class 'int'> 1
<class 'float'> 1.2
<class 'str'> 2.3
<class 'dict'> {'key': 'value'}
<class 'list'> ['element']

# 파일 처리

In [9]:
# =====================================================================================================================================
# 파일에 내용을 기록합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('파일에 내용을 기록합니다.')
sample_file_name = 'sample.csv'
with open(sample_file_name, 'w') as f:
    f.write('C1,C2\n')
    f.write('1,2\n')
# =====================================================================================================================================

# =====================================================================================================================================
# 파일 안의 내용을 확인합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('파일 안의 내용을 확인합니다.')
display(pandas.read_csv(sample_file_name))
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================
# 파일의 내용을 읽습니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('파일의 내용을 읽습니다.')
with open(sample_file_name, 'r') as f:
    print(f.read())
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

# =====================================================================================================================================
# 사용한 파일을 삭제합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('사용한 파일을 삭제합니다.')
os.remove(sample_file_name)
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

----------------------------------------------------------------------------------------------------
파일에 내용을 기록합니다.
----------------------------------------------------------------------------------------------------
파일 안의 내용을 확인합니다.

   C1  C2
0   1   2

----------------------------------------------------------------------------------------------------
파일의 내용을 읽습니다.
C1,C2
1,2

----------------------------------------------------------------------------------------------------
사용한 파일을 삭제합니다.
----------------------------------------------------------------------------------------------------

# 데이터베이스 처리

In [10]:
# =====================================================================================================================================
# 데이터베이스와 연결합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('connect to database')
conn = sqlite3.connect(':memory:')
curs = conn.cursor()
# =====================================================================================================================================

# =====================================================================================================================================
# 테이블을 생성합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('create table')
try:
    curs.execute('drop table sample')
    conn.commit()
except:
    pass
curs.execute('''
create table sample (
    c1      int,
    c2      float,
    c3      text
)
''')
conn.commit()
# =====================================================================================================================================

# =====================================================================================================================================
# 데이터를 입력합니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('insert data to table')
df = pandas.DataFrame([
    {
        'c1': 1,
        'c2': 1.1,
        'c3': '1.1.1',
    },
    {
        'c1': 2,
        'c2': 2.2,
        'c3': '2.2.2',
    },
])
display(df)
df.to_sql('sample', conn, if_exists='append', index=None)

print('----------------------------------------------------------------------------------------------------')
print('check data in table')
df2 = pandas.read_sql('select * from sample', conn)
display(df2)
# =====================================================================================================================================

# =====================================================================================================================================
# 데이터를 읽습니다.
# -------------------------------------------------------------------------------------------------------------------------------------
print('----------------------------------------------------------------------------------------------------')
print('read data in table')
curs.execute('select * from sample')
rs = curs.fetchall()
for row in rs:
    print('c1:[', row[0], '], c2:[', row[1], '], c3:[', row[2], ']')
print('----------------------------------------------------------------------------------------------------')
# =====================================================================================================================================

----------------------------------------------------------------------------------------------------
connect to database
----------------------------------------------------------------------------------------------------
create table
----------------------------------------------------------------------------------------------------
insert data to table

   c1   c2     c3
0   1  1.1  1.1.1
1   2  2.2  2.2.2

----------------------------------------------------------------------------------------------------
check data in table

   c1   c2     c3
0   1  1.1  1.1.1
1   2  2.2  2.2.2

----------------------------------------------------------------------------------------------------
read data in table
c1:[ 1 ], c2:[ 1.1 ], c3:[ 1.1.1 ]
c1:[ 2 ], c2:[ 2.2 ], c3:[ 2.2.2 ]
----------------------------------------------------------------------------------------------------

# 병렬처리

In [11]:
list_param = list()
for idx in range(10):
    dict_param = dict()
    dict_param['index'] = idx
    list_param.append(dict_param)

p = multiprocessing.Pool(3)
# parallel_print 함수에 대한 정의는 .py 파일에 별도로 저장되어 있어야 합니다.
p.map(parallel_print, list_param)

0 START 2022-01-02 18:41:00.632447 0.8836692219038809
1 START 2022-01-02 18:41:00.643424 0.9799055508619428
2 START 2022-01-02 18:41:00.646918 0.37302126464740937
2 FINISH 2022-01-02 18:41:01.023077 0.37302126464740937
3 START 2022-01-02 18:41:01.023457 0.8047271079791651
0 FINISH 2022-01-02 18:41:01.517700 0.8836692219038809
4 START 2022-01-02 18:41:01.518006 0.3702460562364924
1 FINISH 2022-01-02 18:41:01.626022 0.9799055508619428
5 START 2022-01-02 18:41:01.626324 0.10742179682170594
5 FINISH 2022-01-02 18:41:01.736670 0.10742179682170594
6 START 2022-01-02 18:41:01.736835 0.5671033908121413
3 FINISH 2022-01-02 18:41:01.828547 0.8047271079791651
7 START 2022-01-02 18:41:01.828857 0.08229999075249783
4 FINISH 2022-01-02 18:41:01.891719 0.3702460562364924
8 START 2022-01-02 18:41:01.892134 0.21291060238344917
7 FINISH 2022-01-02 18:41:01.913748 0.08229999075249783
9 START 2022-01-02 18:41:01.913963 0.916795533330138
8 FINISH 2022-01-02 18:41:02.105244 0.21291060238344917
6 FINISH 2022-01-02 18:41:02.307643 0.5671033908121413
9 FINISH 2022-01-02 18:41:02.832090 0.916795533330138

[None, None, None, None, None, None, None, None, None, None]